name: hours_tracker
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.0.0+3
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  flutter_screenutil: ^5.0.0-nullsafety.11
  injectable: ^1.1.2
  get_it: ^6.0.0
  meta: ^1.3.0
  equatable: ^2.0.0
  firebase_core: ^1.0.2
  formz: ^0.4.0-nullsafety.0
  pedantic: ^1.9.0
  sailor: ^0.7.1
  cloud_firestore: ^1.0.5

  authentication_repository:
    path: packages/repositories/authentication_repository
  record_repository:
    path: packages/repositories/record_repository

dev_dependencies:
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.1.2
  lint: ^1.5.3

flutter:

  uses-material-design: true